Update to core18 and improve dialog boxes

diff --git a/launcher/launcher b/launcher/launcher
--- a/launcher/launcher
+++ b/launcher/launcher
@@ -1,20 +1,28 @@
 #!/bin/bash
 
 set -e
+set -o pipefail
+
+fail () {
+	yad --width=300 --title="$1" --text="$2" --text-align=center --button=gtk-ok:1 --center
+}
 
 GAMEDIR=quake_shareware
 
 if [ ! -d $SNAP_USER_DATA/$GAMEDIR/shareware ];
 then
-  echo "Game directory doesn't exist"
-  echo "Creating directory"
-  mkdir -p $SNAP_USER_DATA/$GAMEDIR
-  echo "Copying game to directory"
-  cd $SNAP_USER_DATA/$GAMEDIR
-  guiluurve download
-  wget https://archive.org/download/Quake_802/zQUAKE_SW-play.zip -t 5 --timeout 10 || guiluurve nodownload
-  unzip -LL -d shareware zQUAKE_SW-play.zip || guiluurve nozip
-  cp $SNAP/quakespasm.pak $SNAP_USER_DATA/$GAMEDIR/shareware
+	echo "Game directory doesn't exist"
+	echo "Creating directory"
+	mkdir -p $SNAP_USER_DATA/$GAMEDIR
+	echo "Copying game to directory"
+	cd $SNAP_USER_DATA/$GAMEDIR
+	wget https://archive.org/download/Quake_802/zQUAKE_SW-play.zip -t 5 --timeout 10 2>&1 | \
+		perl -p -e '$| = 1; s/^.* +([0-9]+%) +([0-9,.]+[GMKB]) +([0-9hms,.]+).*$/\1\n# Downloading... \2 (\3)/' | \
+		yad --progress --title="Downloading Quake" --width=400 --center --no-buttons --auto-close --auto-kill --on-top --no-escape \
+		|| fail "Network Error" "Could not access network to download game files.\n\nPlease check the network status."
+	unzip -LL -d shareware zQUAKE_SW-play.zip \
+		|| fail "Error" "Could not extract game files.\n\The download may have been corrupted"
+	cp $SNAP/quakespasm.pak $SNAP_USER_DATA/$GAMEDIR/shareware
 fi
 
 cd $SNAP_USER_DATA/$GAMEDIR
